import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { ToastProvider } from "@/components/exceptions/toaster-provider";
import { ConfettiProvider } from "@/components/exceptions/confetti";
import ChatBox from "@/components/chatbot-box";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SmarTea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <ToastProvider />
          <ConfettiProvider />
          <ChatBox />
        </body>
      </html>
    </ClerkProvider>
  );
}
